export const roleTagItems = {
  '백엔드 개발자': '#백엔드 개발자',
  '서버/백엔드 개발자': '#서버/백엔드 개발자',
  '프론트엔드 개발자': '#프론트엔드 개발자',
  '웹 풀스택 개발자': '#웹 풀스택 개발자',
  '안드로이드 개발자': '#안드로이드 개발자',
  'IOS 개발자': '#IOS 개발자',
  '크로스플랫폼 앱개발자': '#크로스플랫폼 앱개발자',
  '게임 클라이언트 개발자': '#게임 클라이언트 개발자',
  '게임 서버 개발자': '#게임 서버 개발자',
  DBA: '#DBA',
  '빅데이터 엔지니어': '#빅데이터 엔지니어',
  '인공지능/머신러닝': '#인공지능/머신러닝',
  'devops/시스템 엔지니어': '#devops/시스템 엔지니어',
  '정보보안 담당자': '#정보보안 담당자',
  'QA 엔지니어': '#QA 엔지니어',
  '개발 PM': '#개발 PM',
  'HW/임베디드': '#HW/임베디드',
  'SW/솔루션': '#SW/솔루션',
  웹퍼블리셔: '#웹퍼블리셔',
  'VR/AR/3D': '#VR/AR/3D',
  블록체인: '#블록체인',
  'CI/BI 로고 디자이너': '#CI/BI 로고 디자이너',
  '광고 디자이너': '#광고 디자이너',
  '게임 디자이너': '#게임 디자이너',
  '서체 디자이너': '#서체 디자이너',
  '웹 디자이너': '#웹 디자이너',
  'UI/UX 디자이너': '#UI/UX 디자이너',
  '영상 디자이너': '#영상 디자이너',
  일러스트레이터: '#일러스트레이터',
  '캐릭터 디자이너': '#캐릭터 디자이너',
  '편집 디자이너': '#편집 디자이너',
  '패키지 디자이너': '#패키지 디자이너',
  '전시 디자이너': '#전시 디자이너',
  컬러리스트: '#컬러리스트',
  클래식: '#클래식',
  JAZZ: '#JAZZ',
  CCM: '#CCM',
  팝: '#팝',
  발라드: '#발라드',
  블루스: '#블루스',
  힙합: '#힙합',
  '컨트리 뮤직': '#컨트리 뮤직',
  '포크 음악': '#포크 음악',
  레게: '#레게',
  디스코: '#디스코',
  '록 음악': '#록 음악',
  '전자 음악': '#전자 음악',
  트로트: '#트로트',
  '일렉트로닉 뮤직': '#일렉트로닉 뮤직',
  로큰롤: '#로큰롤',
} as const;

export type roleTagItemsKey = keyof typeof roleTagItems;
export type roleTagItemsValue =
  (typeof roleTagItems)[keyof typeof roleTagItems];

export const roleTagItemsColors: Record<roleTagItemsKey, string> = {
  '백엔드 개발자': 'text-darkgray text-[12px] rounded-full',
  '서버/백엔드 개발자': 'text-darkgray text-[12px] rounded-full',
  '프론트엔드 개발자': 'text-darkgray text-[12px] rounded-full',
  '웹 풀스택 개발자': 'text-darkgray text-[12px] rounded-full',
  '안드로이드 개발자': 'text-darkgray text-[12px] rounded-full',
  'IOS 개발자': 'text-darkgray text-[12px] rounded-full',
  '크로스플랫폼 앱개발자': 'text-darkgray text-[12px] rounded-full',
  '게임 클라이언트 개발자': 'text-darkgray text-[12px] rounded-full',
  '게임 서버 개발자': 'text-darkgray text-[12px] rounded-full',
  DBA: 'text-darkgray text-[12px] rounded-full',
  '빅데이터 엔지니어': 'text-darkgray text-[12px] rounded-full',
  '인공지능/머신러닝': 'text-darkgray text-[12px] rounded-full',
  'devops/시스템 엔지니어': 'text-darkgray text-[12px] rounded-full',
  '정보보안 담당자': 'text-darkgray text-[12px] rounded-full',
  'QA 엔지니어': 'text-darkgray text-[12px] rounded-full',
  '개발 PM': 'text-darkgray text-[12px] rounded-full',
  'HW/임베디드': 'text-darkgray text-[12px] rounded-full',
  'SW/솔루션': 'text-darkgray text-[12px] rounded-full',
  웹퍼블리셔: 'text-darkgray text-[12px] rounded-full',
  'VR/AR/3D': 'text-darkgray text-[12px] rounded-full',
  블록체인: 'text-darkgray text-[12px] rounded-full',
  'CI/BI 로고 디자이너': 'text-darkgray text-[12px] rounded-full',
  '광고 디자이너': 'text-darkgray text-[12px] rounded-full',
  '게임 디자이너': 'text-darkgray text-[12px] rounded-full',
  '서체 디자이너': 'text-darkgray text-[12px] rounded-full',
  '웹 디자이너': 'text-darkgray text-[12px] rounded-full',
  'UI/UX 디자이너': 'text-darkgray text-[12px] rounded-full',
  '영상 디자이너': 'text-darkgray text-[12px] rounded-full',
  일러스트레이터: 'text-darkgray text-[12px] rounded-full',
  '캐릭터 디자이너': 'text-darkgray text-[12px] rounded-full',
  '편집 디자이너': 'text-darkgray text-[12px] rounded-full',
  '패키지 디자이너': 'text-darkgray text-[12px] rounded-full',
  '전시 디자이너': 'text-darkgray text-[12px] rounded-full',
  컬러리스트: 'text-darkgray text-[12px] rounded-full',
  클래식: 'text-darkgray text-[12px] rounded-full',
  JAZZ: 'text-darkgray text-[12px] rounded-full',
  CCM: 'text-darkgray text-[12px] rounded-full',
  팝: 'text-darkgray text-[12px] rounded-full',
  발라드: 'text-darkgray text-[12px] rounded-full',
  블루스: 'text-darkgray text-[12px] rounded-full',
  힙합: 'text-darkgray text-[12px] rounded-full',
  '컨트리 뮤직': 'text-darkgray text-[12px] rounded-full',
  '포크 음악': 'text-darkgray text-[12px] rounded-full',
  레게: 'text-darkgray text-[12px] rounded-full',
  디스코: 'text-darkgray text-[12px] rounded-full',
  '록 음악': 'text-darkgray text-[12px] rounded-full',
  '전자 음악': 'text-darkgray text-[12px] rounded-full',
  트로트: 'text-darkgray text-[12px] rounded-full',
  '일렉트로닉 뮤직': 'text-darkgray text-[12px] rounded-full',
  로큰롤: 'text-darkgray text-[12px] rounded-full',
} as const;
