export const skillTagItems = {
  // 개발자 스킬
  React: '#React',
  TypeScript: '#TypeScript',
  JavaScript: '#JavaScript',
  'Node.js': '#Node.js',
  'Express.js': '#Express.js',
  Python: '#Python',
  Django: '#Django',
  Flask: '#Flask',
  'Ruby on Rails': '#RubyOnRails',
  Java: '#Java',
  'Spring Boot': '#SpringBoot',
  'C++': '#C++',
  'C#': '#C#',
  Go: '#Go',
  Rust: '#Rust',
  GraphQL: '#GraphQL',
  MongoDB: '#MongoDB',
  MySQL: '#MySQL',
  PostgreSQL: '#PostgreSQL',
  Docker: '#Docker',

  // 아티스트 스킬
  MIDI: '#MIDI',
  Cubase: '#Cubase',
  Synthesizers: '#Synthesizers',
  Sampling: '#Sampling',
  'Vocal Tuning': '#VocalTuning',
  'Field Recording': '#FieldRecording',
  'Game Audio Implementation': '#GameAudioImplementation',
  Melodyne: '#Melodyne',
  'Ableton Live': '#AbletonLive',
  'FL Studio': '#FLStudio',
  'Logic Pro': '#LogicPro',
  'Pro Tools': '#ProTools',

  // 디자이너 스킬
  'UX/UI Design': '#UXUIDesign',
  'Visual Design': '#VisualDesign',
  Wireframing: '#Wireframing',
  Prototyping: '#Prototyping',
  'Interaction Design': '#InteractionDesign',
  'Adobe Photoshop': '#AdobePhotoshop',
  'Adobe Illustrator': '#AdobeIllustrator',
  'Adobe XD': '#AdobeXD',
  Figma: '#Figma',
  Sketch: '#Sketch',
  'Motion Graphics': '#MotionGraphics',
  'After Effects': '#AfterEffects',
  'Brand Identity Design': '#BrandIdentityDesign',
  Typography: '#Typography',
  '3D Modeling': '#3DModeling',
  Blender: '#Blender',
  'Cinema 4D': '#Cinema4D',
  'Web Design': '#WebDesign',
  'Responsive Design': '#ResponsiveDesign',
  'Design Systems': '#DesignSystems',
};

export type skillTagItemsKey = keyof typeof skillTagItems;

export const skillTagItmesColors: Record<skillTagItemsKey, string> = {
  // 개발자 스킬
  React: 'text-darkgray text-[12px] rounded-full',
  TypeScript: 'text-darkgray text-[12px] rounded-full',
  JavaScript: 'text-darkgray text-[12px] rounded-full',
  'Node.js': 'text-darkgray text-[12px] rounded-full',
  'Express.js': 'text-darkgray text-[12px] rounded-full',
  Python: 'text-darkgray text-[12px] rounded-full',
  Django: 'text-darkgray text-[12px] rounded-full',
  Flask: 'text-darkgray text-[12px] rounded-full',
  'Ruby on Rails': 'text-darkgray text-[12px] rounded-full',
  Java: 'text-darkgray text-[12px] rounded-full',
  'Spring Boot': 'text-darkgray text-[12px] rounded-full',
  'C++': 'text-darkgray text-[12px] rounded-full',
  'C#': 'text-darkgray text-[12px] rounded-full',
  Go: 'text-darkgray text-[12px] rounded-full',
  Rust: 'text-darkgray text-[12px] rounded-full',
  GraphQL: 'text-darkgray text-[12px] rounded-full',
  MongoDB: 'text-darkgray text-[12px] rounded-full',
  MySQL: 'text-darkgray text-[12px] rounded-full',
  PostgreSQL: 'text-darkgray text-[12px] rounded-full',
  Docker: 'text-darkgray text-[12px] rounded-full',

  // 아티스트 스킬
  MIDI: 'text-darkgray text-[12px] rounded-full',
  Cubase: 'text-darkgray text-[12px] rounded-full',
  Synthesizers: 'text-darkgray text-[12px] rounded-full',
  Sampling: 'text-darkgray text-[12px] rounded-full',
  'Vocal Tuning': 'text-darkgray text-[12px] rounded-full',
  'Field Recording': 'text-darkgray text-[12px] rounded-full',
  'Game Audio Implementation': 'text-darkgray text-[12px] rounded-full',
  Melodyne: 'text-darkgray text-[12px] rounded-full',
  'Ableton Live': 'text-darkgray text-[12px] rounded-full',
  'FL Studio': 'text-darkgray text-[12px] rounded-full',
  'Logic Pro': 'text-darkgray text-[12px] rounded-full',
  'Pro Tools': 'text-darkgray text-[12px] rounded-full',

  // 디자이너 스킬
  'UX/UI Design': 'text-darkgray text-[12px] rounded-full',
  'Visual Design': 'text-darkgray text-[12px] rounded-full',
  Wireframing: 'text-darkgray text-[12px] rounded-full',
  Prototyping: 'text-darkgray text-[12px] rounded-full',
  'Interaction Design': 'text-darkgray text-[12px] rounded-full',
  'Adobe Photoshop': 'text-darkgray text-[12px] rounded-full',
  'Adobe Illustrator': 'text-darkgray text-[12px] rounded-full',
  'Adobe XD': 'text-darkgray text-[12px] rounded-full',
  Figma: 'text-darkgray text-[12px] rounded-full',
  Sketch: 'text-darkgray text-[12px] rounded-full',
  'Motion Graphics': 'text-darkgray text-[12px] rounded-full',
  'After Effects': 'text-darkgray text-[12px] rounded-full',
  'Brand Identity Design': 'text-darkgray text-[12px] rounded-full',
  Typography: 'text-darkgray text-[12px] rounded-full',
  '3D Modeling': 'text-darkgray text-[12px] rounded-full',
  Blender: 'text-darkgray text-[12px] rounded-full',
  'Cinema 4D': 'text-darkgray text-[12px] rounded-full',
  'Web Design': 'text-darkgray text-[12px] rounded-full',
  'Responsive Design': 'text-darkgray text-[12px] rounded-full',
  'Design Systems': 'text-darkgray text-[12px] rounded-full',
};
