export type HubSkillTagVariant =
  // 프로그래머 스킬
  | 'React'
  | 'TypeScript'
  | 'JavaScript'
  | 'Node.js'
  | 'Express.js'
  | 'Python'
  | 'Django'
  | 'Flask'
  | 'Ruby on Rails'
  | 'Java'
  | 'Spring Boot'
  | 'C++'
  | 'C#'
  | 'Go'
  | 'Rust'
  | 'GraphQL'
  | 'MongoDB'
  | 'MySQL'
  | 'PostgreSQL'
  | 'Docker'

  // 아티스트 스킬
  | 'Music Theory'
  | 'Audio Mixing'
  | 'Audio Mastering'
  | 'Sound Design'
  | 'Composing'
  | 'Arranging'
  | 'Music Production'
  | 'Digital Audio Workstations (DAWs)'
  | 'Ableton Live'
  | 'FL Studio'
  | 'Logic Pro'
  | 'Pro Tools'
  | 'Cubase'
  | 'Melodyne'
  | 'Sampling'
  | 'MIDI Programming'
  | 'Synthesizers'
  | 'Vocal Tuning'
  | 'Field Recording'
  | 'Game Audio Implementation'

  // 디자이너 스킬
  | 'UX/UI Design'
  | 'Visual Design'
  | 'Wireframing'
  | 'Prototyping'
  | 'Interaction Design'
  | 'Adobe Photoshop'
  | 'Adobe Illustrator'
  | 'Adobe XD'
  | 'Figma'
  | 'Sketch'
  | 'Motion Graphics'
  | 'After Effects'
  | 'Brand Identity Design'
  | 'Typography'
  | '3D Modeling'
  | 'Blender'
  | 'Cinema 4D'
  | 'Web Design'
  | 'Responsive Design'
  | 'Design Systems';

export interface HubSkillTagProps {
  label: string;
  variant: HubSkillTagVariant;
}
