export const API_PATH = {
  login: '/auth/:provider/callback',
  updateToken: '/auth/refresh',
  roleSelect: '/auth/roleselect',
  channel: 'chat/channels/:id',
  channelMessages: 'chat/channels/:id/messages',
  createGroup: '/channel/group',
  feeds: '/feeds',
  feed: '/feed',
  feedDetail: '/feed/:id',
  feedChats: '/feed/:id/comments',
  feedChat: '/feed/:id/comment',
  feedChatDelete: '/feed/:id/comment/:commentId',
  projects: '/projects',
  project: '/projects/:projectId',
  hubWeeklyBest: '/projects/popular-this-week',
  feedLike: '/feed/:id/likes',
  feedImage: '/feed/image',
  searchMessages: '/chat/channels/:id/messages/search',
  feedRank: '/feed/weekly',
  hubBookmark: '/projects/:projectId/bookmark',
  hubImage: '/projects/image',
};
