export const API_PATH = {
  login: '/auth/:provider/callback',
  updateToken: '/auth/refresh',
  roleSelect: '/auth/roleselect',
  channel: 'chat/channels/:channelId',
  channelMessages: 'chat/channels/:channelId/messages',
  createGroup: '/channel/group',
  feeds: '/feeds',
  feed: '/feed',
  feedDetail: '/feed/:id',
  feedChats: '/feed/:id/comments',
  feedChat: '/feed/:id/comment',
  feedChatDelete: '/feed/:id/comment/:commentId',
  connectionhub: '/connectionhub',
  connectionhubdetail: '/connectionhubdetail',
  feedLike: '/feed/:id/likes',
  feedImage: '/feed/image',
  searchMessages: '/chat/channels/:channelId/messages/search',
  feedRank: '/feed/weekly',
  project: '/projects',
};
